<?php
/**
 */

namespace execut\alias\bootstrap;


use execut\alias\Attacher;

abstract class Web extends Common
{
    public function bootstrap($app)
    {
        parent::bootstrap($app); // TODO: Change the autogenerated stub
        $this->attach();
    }

    protected function attach()
    {
        $models = \yii::$app->getModule('alias')->getModels();
        foreach ($models as $model) {
            $class = $model['modelClass'];
            $attacher = new Attacher([
                'tables' => [
                    $class::tableName()
                ],
            ]);
        }

        $attacher->safeUp();
    }
}